export const INIT_LAWYERS = 'INIT_LAWYERS';
export const ADD_LAWYER = 'ADD_LAWYER';
export const ADD_INQUIRER = 'ADD_INQUIRER';

export const INIT_INQUIRERS = 'INIT_INQUIRERS';
export const UPDATE_INQUIRERS = 'UPDATE_INQUIRERS';

export const INIT_CONSULTATIONS = 'INIT_CONSULTATIONS'
export const CONSULTATION_CREATED = 'CONSULTATION_CREATED'
export const CONSULTATION_UPDATED = 'CONSULTATION_UPDATED'
export const CONSULTATION_DELETED = 'CONSULTATION_DELETED'

export const INIT_LAW_TYPES = 'INIT_LAW_TYPES';
