export const INIT_LAWYERS = 'INIT_LAWYERS';
export const INIT_INQUIRERS = 'INIT_INQUIRERS';
export const SET_CURRENT_INQUIRERS = 'SET_CURRENT_INQUIRERS';
export const SET_CURR_INQS_PAST_CONSULTS = 'SET_CURR_INQS_PAST_CONSULTS';

export const INIT_CONSULTATIONS = 'INIT_CONSULTATIONS';
export const CONSULTATION_CREATED = 'CONSULTATION_CREATED';
export const CONSULTATION_IN_PROGRESS = 'CONSULTATION_IN_PROGRESS';

export const INIT_LAW_TYPES = 'INIT_LAW_TYPES';

export const SET_CLINIC_SETTINGS = 'SET_CLINIC_SETTINGS';
export const SET_CURRENT_CLINIC = 'SET_CURRENT_CLINIC';
